### PR TITLE
Added assets-target option in package extra section

### PR DESCRIPTION
**Pull request by pdima88**

### CODE REVIEW

**Comment by janpecha** [comment]
Thanks :) What is the use case for this feature?

**Comment by pdima88** [comment]
I can use it if I want to store assets from package in path, different from package name, for example i have package (maintainer)/(package_name), so assets will be stored by default in (assets-dir)/(maintainer)/(package_name) but I want to store assets in shorter path: (assets-dir)/(package_name), I can use assets-target: "(package_name)" in `extra` section of package config

**Comment by pdima88** [comment]
Added feature: if assets-target option in package config contains absolute path - it will be used as relative to project dir: This can be used to store package assets files out of `assets-dir`

**Comment by janpecha** [comment]
I'm not sure if `assets-target` in package extra section is good idea :-/ From my point of view it solves a very specific use case. Moreover difference between absolute and relative path can be a little bit confusing :-/

Maybe would be better add new option `assets-shortpaths: true/false` for root package. If it will be set to `true`, installer will use `<assets-dir>/<package-name>` instead of `<assets-dir>/<vendor-name>/<package-name>`. What do you think?

**Comment by pdima88** [comment]
> I'm not sure if `assets-target` in package extra section is good idea :-/ From my point of view it solves a very specific use case. Moreover difference between absolute and relative path can be a little bit confusing :-/
> Maybe would be better add new option `assets-shortpaths: true/false` for root package. If it will be set to `true`, installer will use `<assets-dir>/<package-name>` instead of `<assets-dir>/<vendor-name>/<package-name>`. What do you think?

From root package I already can set any `assets-target`, no need any extra option like `assets-shortpaths: true/false`. But I want to set up assets-target from package, to install package simply with `composer require`, without additional root package config edit

**Pull request closed without merging**
